// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwPCi3eFuoponvqvf4cGlCu7nTuwHkOow',
    appId: '1:643935084045:web:bdf1bba4316f3759017f44',
    messagingSenderId: '643935084045',
    projectId: 'modiin4u-a895f',
    authDomain: 'modiin4u-a895f.firebaseapp.com',
    storageBucket: 'modiin4u-a895f.firebasestorage.app',
    measurementId: 'G-YZKV3926G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVU4DHGN3PvwtS6ZJJWqrPdsRriFXm4JY',
    appId: '1:643935084045:android:0a7427a56e6c5c4c017f44',
    messagingSenderId: '643935084045',
    projectId: 'modiin4u-a895f',
    storageBucket: 'modiin4u-a895f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApDcCTRUx62nIwqjr3mzIbgNRkiHqwrOY',
    appId: '1:643935084045:ios:ec507536ca74e8cf017f44',
    messagingSenderId: '643935084045',
    projectId: 'modiin4u-a895f',
    storageBucket: 'modiin4u-a895f.firebasestorage.app',
    iosBundleId: 'il.co.modiin4u.modiin4u',
  );
}
