#!/usr/bin/env python3
"""Turn the WordPress export into SQL for the Supabase schema.

The app currently reads bundled JSON, which is read-only — nothing in the
admin can change what the site shows. This writes the same content into the
tables defined in supabase/migrations, so the admin and the app can share
one source of truth.

Ids are uuid5 of the WordPress post id, so re-running updates rows instead
of duplicating them, and a second import after a fresh export is safe.

Usage:  python3 tool/build_seed.py ~/Downloads/WordPress.2026-09-16.xml
Writes: supabase/seed_content.sql
"""

import html
import os
import re
import sys
import urllib.parse
import uuid
import xml.etree.ElementTree as ET

NS = {
    'wp': 'http://wordpress.org/export/1.2/',
    'content': 'http://purl.org/rss/1.0/modules/content/',
    'excerpt': 'http://wordpress.org/export/1.2/excerpt/',
}

# Stable namespace so ids never change between runs.
NAMESPACE = uuid.UUID('6f9619ff-8b86-d011-b42d-00c04fc964ff')
LATLNG = re.compile(r'^[0-9a-f]{32}_(lat|lng)$')
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'supabase', 'seed_content.sql')

# Campaign tags, not categories — they out-count the real ones.
def is_campaign(term):
    return 'מלחמת' in term


def uid(kind, wp_id):
    return str(uuid.uuid5(NAMESPACE, '%s:%s' % (kind, wp_id)))


def q(v):
    """SQL literal. None/'' becomes NULL so not-null defaults still apply."""
    if v is None or v == '':
        return 'null'
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def plain(s, limit=None):
    if not s:
        return ''
    s = re.sub(r'<(script|style)[^>]*>.*?</\1>', ' ', s, flags=re.S | re.I)
    s = re.sub(r'<[^>]+>', ' ', s)
    s = html.unescape(s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s[:limit] if limit else s


def slug_of(link, fallback_id):
    """WordPress percent-encodes Hebrew slugs. Decoding them back keeps the
    slug readable and matches the live site; truncating the encoded form
    instead used to cut mid-escape and leave a dangling '%9'."""
    m = re.search(r'/([^/]+)/?$', (link or '').rstrip('/'))
    s = urllib.parse.unquote(m.group(1)) if m else ''
    s = re.sub(r'[\s/]+', '-', s).strip('-')[:120]
    return s or 'post-%s' % fallback_id


def parse(src):
    attachments, items = {}, {'news': [], 'business': []}
    for _, el in ET.iterparse(src, events=('end',)):
        if el.tag != 'item':
            continue
        ptype = el.findtext('wp:post_type', '', NS)
        pid = el.findtext('wp:post_id', '', NS)

        if ptype == 'attachment':
            url = el.findtext('wp:attachment_url', '', NS)
            if pid and url:
                attachments[pid] = url
            el.clear()
            continue

        if ptype not in items or el.findtext('wp:status', '', NS) != 'publish':
            el.clear()
            continue

        meta, lat, lng = {}, None, None
        for pm in el.findall('wp:postmeta', NS):
            k = pm.findtext('wp:meta_key', '', NS) or ''
            v = (pm.findtext('wp:meta_value', '', NS) or '').strip()
            if not v:
                continue
            m = LATLNG.match(k)
            if m:
                lat, lng = (v, lng) if m.group(1) == 'lat' else (lat, v)
            elif not k.startswith(('_elementor', '_edit', '_yoast', '_oembed', '_wp_old')):
                meta[k] = v

        items[ptype].append({
            'id': int(pid),
            'title': plain(el.findtext('title', '')),
            'link': el.findtext('link', ''),
            'date': el.findtext('wp:post_date_gmt', '', NS) or el.findtext('wp:post_date', '', NS),
            'body': el.findtext('content:encoded', '', NS) or '',
            'excerpt': plain(el.findtext('excerpt:encoded', '', NS), 400),
            'terms': [t.text for t in el.findall('category') if t.text],
            'meta': meta,
            'lat': lat,
            'lng': lng,
        })
        el.clear()
    return attachments, items


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    attachments, items = parse(os.path.expanduser(sys.argv[1]))

    # businesses.slug and articles.slug are unique; the export has a few
    # collisions, so suffix the later ones rather than lose the row.
    for key in items:
        used = set()
        for it in items[key]:
            base = slug_of(it['link'], it['id'])
            slug, n = base, 2
            while slug in used:
                slug, n = '%s-%d' % (base, n), n + 1
            used.add(slug)
            it['slug'] = slug

    lines = [
        '-- Generated by tool/build_seed.py — do not edit by hand.',
        '-- Re-runnable: ids are uuid5 of the WordPress post id, so a second',
        '-- import updates rows rather than duplicating them.',
        'begin;',
        '',
    ]

    # ── categories ──────────────────────────────────────────────
    cats = {}   # (scope, name) -> id
    for scope, key in (('business', 'business'), ('article', 'news')):
        seen = []
        for it in items[key]:
            for t in it['terms']:
                if t == 'עסקים באתר' or is_campaign(t) or (scope, t) in cats:
                    continue
                cats[(scope, t)] = uid('cat', '%s:%s' % (scope, t))
                seen.append(t)
        for i, name in enumerate(seen):
            lines.append(
                "insert into categories (id, scope, name, slug, sort_order) values "
                "(%s, %s, %s, %s, %d) on conflict (id) do update set name = excluded.name;"
                % (q(cats[(scope, name)]), q(scope), q(name),
                   q(uid('slug', '%s:%s' % (scope, name))[:8] + '-' + str(i)), i))
    lines.append('')

    # ── businesses ──────────────────────────────────────────────
    for b in items['business']:
        m = b['meta']
        bid = uid('business', b['id'])
        gallery = [attachments[x] for x in m.get('photos-gallery', '').split(',') if x.strip() in attachments]
        cover = attachments.get(m.get('_thumbnail_id', '')) or (gallery[0] if gallery else None)
        rating = m.get('_jet_reviews_average_rating')
        lines.append(
            "insert into businesses (id, name, slug, short_description, full_description, phone, "
            "website, address, latitude, longitude, logo_url, cover_url, rating, kosher_level, "
            "has_delivery, open_on_shabbat, status, is_verified) values (%s, %s, %s, %s, %s, %s, %s, "
            "%s, %s, %s, %s, %s, %s, %s, %s, %s, 'active', true) on conflict (id) do update set "
            "name = excluded.name, phone = excluded.phone, address = excluded.address, "
            "latitude = excluded.latitude, longitude = excluded.longitude, "
            "cover_url = excluded.cover_url, rating = excluded.rating, updated_at = now();"
            % (q(bid), q(m.get('business-name') or b['title']), q(b['slug']),
               q(plain(m.get('_description', ''), 300)), q(plain(m.get('business-incloud', ''))),
               q(re.sub(r'[‎‏‪-‮\s]', '', m.get('phone', ''))),
               q(m.get('business-site')), q(m.get('address') or m.get('adress') or 'מודיעין'),
               q(float(b['lat']) if b['lat'] else None), q(float(b['lng']) if b['lng'] else None),
               q(attachments.get(m.get('business-logo', ''))), q(cover),
               q(float(rating) if rating else 0),
               q('rabbanut' if str(m.get('kosher-unkosher')).lower() == 'true' else 'none'),
               q(str(m.get('delivery')).lower() == 'true'),
               q(any('פתוח בשבת' in t for t in b['terms']))))
        for t in b['terms']:
            if ('business', t) in cats:
                lines.append(
                    "insert into entity_categories (entity_type, entity_id, category_id) values "
                    "('business', %s, %s) on conflict do nothing;" % (q(bid), q(cats[('business', t)])))
    lines.append('')

    # ── articles ────────────────────────────────────────────────
    for a in items['news']:
        aid = uid('article', a['id'])
        body = a['body'].strip() or a['excerpt'] or a['title']
        lines.append(
            "insert into articles (id, title, slug, body, excerpt, featured_image, status, "
            "published_at) values (%s, %s, %s, %s, %s, %s, 'published', %s) "
            "on conflict (id) do update set title = excluded.title, body = excluded.body, "
            "excerpt = excluded.excerpt, featured_image = excluded.featured_image, updated_at = now();"
            % (q(aid), q(a['title']), q(a['slug']), q(body), q(a['excerpt']),
               q(attachments.get(a['meta'].get('_thumbnail_id', ''))), q(a['date'])))
        for t in a['terms']:
            if ('article', t) in cats:
                lines.append(
                    "insert into entity_categories (entity_type, entity_id, category_id) values "
                    "('article', %s, %s) on conflict do nothing;" % (q(aid), q(cats[('article', t)])))

    lines += ['', 'commit;', '']
    path = os.path.abspath(OUT)
    open(path, 'w', encoding='utf-8').write('\n'.join(lines))

    print('categories : %d' % len(cats))
    print('businesses : %d' % len(items['business']))
    print('articles   : %d' % len(items['news']))
    print('-> %s (%.1f MB)' % (path, os.path.getsize(path) / 1e6))


if __name__ == '__main__':
    main()
